// SPDX-License-Identifier: GPL-3.0-or-later
import {zipSync,strToU8} from 'three/addons/libs/fflate.module.js';
import {frameRole,finishes} from './finishes.js';
const utf8=x=>strToU8(typeof x==='string'?x:JSON.stringify(x,null,2)+'\n');
const decode=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const xml=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
export function selectedParts(config,registry,half='both',scope='shells'){
 const parts=[];for(const side of ['left','right']){if(half!=='both'&&side!==half)continue;const cs=config.cases[side],f=config.frames[side];for(const group of ['base','plate'])parts.push({...registry.assets[`${side}-case-${cs.style}-${group}`],side,colors:{body:cs[group+'_color']}});if(cs.cover)parts.push({...registry.assets[`${side}-frame-${f.style}`],side,style:f.style,colors:{body:f.color,...f.accents}});if(scope==='complete')for(const id of registry.supports)parts.push({...registry.assets[`${side}-${id}`],side,colors:{body:'#78908a'}});}return parts;
}
export function mesh3MF(part){
 const bytes=decode(part.stl),view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),n=view.getUint32(80,true);if(bytes.length!==84+50*n)throw Error('Expected a binary STL.');
 const vertexIds=new Map(),points=[],triangles=[],roles=[],minimum=[Infinity,Infinity,Infinity];for(let t=0;t<n;t++){const ids=[];for(let j=0;j<3;j++){const p=[0,1,2].map(a=>view.getFloat32(84+t*50+12+j*12+a*4,true));p.forEach((v,a)=>minimum[a]=Math.min(minimum[a],v));const key=p.join(',');if(!vertexIds.has(key)){vertexIds.set(key,points.length);points.push(p);}ids.push(vertexIds.get(key));}triangles.push(ids);const center=[0,1,2].map(a=>ids.reduce((sum,i)=>sum+points[i][a],0)/3);roles.push(part.style?frameRole(part.style,part.side,center[0],center[2],-center[1]):0);}
 const shift=minimum.map((v,i)=>(i===2?0:10)-v),colors=finishes.roles.map(role=>part.colors[role]||part.colors.body),paint=['4','8','0C','1C'];
 const vertices=points.map(p=>`<vertex x="${p[0]+shift[0]}" y="${p[1]+shift[1]}" z="${p[2]+shift[2]}"/>`).join('');
 const faces=triangles.map((a,i)=>`<triangle v1="${a[0]}" v2="${a[1]}" v3="${a[2]}" pid="1" p1="${roles[i]}" paint_color="${paint[roles[i]]}"/>`).join('');
 const model=`<?xml version="1.0" encoding="UTF-8"?><model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:m="http://schemas.microsoft.com/3dmanufacturing/material/2015/02" requiredextensions="m"><metadata name="Application">Flan36</metadata><metadata name="Title">${xml(part.id)}</metadata><metadata name="Description">Flan36 prototype geometry. Verify orientation, supports, captive inserts and process before slicing.</metadata><resources><m:colorgroup id="1">${colors.map(c=>`<m:color color="${c.toUpperCase()}FF"/>`).join('')}</m:colorgroup><object id="2" type="model" name="${xml(part.id)}" pid="1" pindex="0"><mesh><vertices>${vertices}</vertices><triangles>${faces}</triangles></mesh></object></resources><build><item objectid="2"/></build></model>`;
 const files={'[Content_Types].xml':utf8('<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/></Types>'),'_rels/.rels':utf8('<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/></Relationships>'),'3D/3dmodel.model':utf8(model),'Metadata/model_settings.config':utf8('<?xml version="1.0"?><config><object id="2"><metadata key="name" value="'+xml(part.id)+'"/><metadata key="extruder" value="1"/></object></config>')};
 return {bytes:zipSync(files,{level:6}),translation_mm:shift,triangles:n,role_triangles:finishes.roles.map((role,i)=>({role,count:roles.filter(v=>v===i).length,color:colors[i]}))};
}
export async function printKit(config,registry,{half='both',scope='shells',progress=()=>{}}={}){
 const selected=selectedParts(config,registry,half,scope),files={},records=[];
 for(const [i,p] of selected.entries()){progress(i+1,selected.length);await new Promise(requestAnimationFrame);const colored=mesh3MF(p);files[`STL/${p.id}.stl`]=decode(p.stl);files[`3MF/${p.id}.3mf`]=colored.bytes;records.push({id:p.id,side:p.side,quantity:1,source:p.path,source_sha256:p.sha256,colors:p.colors,translation_3mf_mm:colored.translation_mm,triangles:colored.triangles,role_triangles:colored.role_triangles});}
 const manifest={schema:1,revision:'I',units:'mm',status:'Prototype geometry; physical fit and joining untested',half,scope,parts:records,configuration:config,joining:registry.joining,source:'https://github.com/eduarbo/flan36',license:'GPL-3.0-or-later',excludes:'Commercial electronics, cells, hardware, feet and KLP keycaps. View visibility and exploded offsets do not affect this kit.'};
 files['manifest.json']=utf8(manifest);files['Flan36-config.json']=utf8(config);files['READ-ME.txt']=utf8(`FLAN36 / PRINT KIT / mm\n\nSTL: exact native CAD exports in assembly coordinates.\n3MF: same triangles translated onto Z=0; translation and colors in manifest.json.\nOne file per physical part. No printer profile, G-code or verified print process.\n\nJOINING\nEach half: 3 M2x6 and 2 M2x4 screws; tap 1.7 mm pilot holes to M2.\nInstalled frame: 3 captive 2x3 mm magnets and 3 ferromagnetic 2x4 mm pins.\nCapture inserts during printing; inspect cavities and plan insertion pauses.\nNo clips are modeled. Complete printed set includes 3 washers per half.\n\nColors are surface regions, not separate loose inlays. Bambu Studio retains the painted regions but does not automatically restore this\ngeneric file's palette. Add four filaments in body/detail/accent/secondary order,\nusing the manifest colors, then inspect every region. Automatic palette import is\nnot verified. Select your actual filament materials and process before slicing. Materials and process are your choices.\n\nhttps://github.com/eduarbo/flan36/blob/main/docs/customize.md\nGPL-3.0-or-later; see repository LICENSE.\n`);
 return {bytes:zipSync(files,{level:6}),manifest};
}
